// Generated by Wrangler
// After adding bindings to `wrangler.jsonc`, regenerate this interface via `npm run cf-typegen`
import { PathPattern } from './src/utils/pathUtils';
import { EnvVariables } from './src/config/environmentConfig';

interface Env extends EnvVariables {
  // Define environment variables from wrangler.jsonc
  ENVIRONMENT?: string;
  PATH_PATTERNS?: PathPattern[] | string;
  VERSION?: string;
}
